# Generated by Django 4.2.20 on 2025-03-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Rag_System_App", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faissfile",
            name="file",
        ),
    ]
